services:
  fastapi_backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: resume_fastapi
    container_name: resume_backend
    volumes:
      - ./.env:/app/.env:ro
    environment:
      - PYTHONPATH=/app/src
    ports:
        - "8000:8000"
  
  react_frontend:
    build:
      context: ./src/openai_sdk_resume_assistant/react-frontend
      dockerfile: Dockerfile
    image: resume_react_frontend
    container_name: resume_frontend
    ports:
      - "5173:5173"
    depends_on:
      - fastapi_backend